# Generated by Django 2.2.7 on 2019-11-24 02:35

from django.db import migrations

from markdownfield.models import RenderedMarkdownField


class Migration(migrations.Migration):

    dependencies = [
        ('foxtail_blog', '0005_comment_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text_rendered',
            field=RenderedMarkdownField(editable=False),
        ),
    ]
