version: 2.1
jobs:
  run_tests:
    docker:
      - image: circleci/python:3.7
        environment:
          PYTHONDONTWRITEBYTECODE: TRUE
    steps:
      - checkout
      - run:
          name: Installing dependencies
          command: |
            pip install --user -r testing/requirements.txt
      - run:
          name: Running tests
          command: |
            mkdir test-reports
            python -m pytest --junitxml=test-reports/junit.xml foxtail_blog
      - store_test_results:
          path: test-reports
workflows:
  version: 2
  test:
    jobs:
      - run_tests